- id: doi:10.1038/s41592-021-01259-4
  image: images/tools/enformer.png
  authors:
  - '<b>YY Lu</b>'
  - WS Noble
  extra-links:
    - link: https://rdcu.be/cyMvt
      text: Paper
  tags:
    - Computational Genomics

- id: url:https://proceedings.mlr.press/v139/lu21b.html
  image: images/tools/icml21.jpg
  title: 'DANCE: Enhancing saliency maps using decoys'
  authors:
  - '<b>YY Lu*</b>'
  - 'W Guo*'
  - X Xing
  - WS Noble
  publisher: Proceedings of International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21b.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/dance
      text: Code
    - type: docs
      link: https://slideslive.com/38959260/dance-enhancing-saliency-maps-using-decoys
      text: Slides
  tags:
    - Interpretable Machine Learning

- id: url:https://proceedings.mlr.press/v139/lu21e.html
  image: images/tools/icml21.jpg
  title: 'ACE: Explaining cluster from an adversarial perspective'
  authors:
  - '<b>YY Lu</b>'
  - T Yu
  - G Bonora
  - WS Noble
  publisher: Proceedings of International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21e.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/ace
      text: Code
    - type: docs
      link: https://slideslive.com/38959455/ace-explaining-cluster-from-an-adversarial-perspective
      text: Slides
    - type: data
      link: http://noble.gs.washington.edu/proj/ACE
      text: Datasets
  tags:
    - Interpretable Machine Learning
    - Computational Genomics
    - Single-cell Genomics

- id: doi:10.1093/bioinformatics/btab284
  image: images/tools/bioinfo_diameter.jpg
  authors:
  - '<b>YY Lu</b>'
  - J Bilmes
  - RA Rodriguez-Mias
  - J Villen
  - WS Noble
  extra-links:
    - link: https://academic.oup.com/bioinformatics/article/37/Supplement_1/i434/6319661
      text: Paper
    - type: source
      link: http://crux.ms/
      text: Code
    - type: docs
      link: files/pubs/diameter_slides.pdf
      text: Slides
    - type: data
      link: http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD025385
      text: Datasets
  tags:
    - Computational Proteomics
    - Mass Spectrometry

- id: doi:10.1093/bioinformatics/btaa699
  image: images/tools/bioinfo_craft.jpg
  authors:
  - '<b>YY Lu*</b>'
  - 'J Bai*'
  - Y Wang
  - Y Wang
  - F Sun
  extra-links:
    - link: https://academic.oup.com/bioinformatics/article/37/2/155/5885078
      text: Paper
    - type: source
      link: https://github.com/jiaxingbai/CRAFT
      text: Code
  tags:
    - Computational Genomics
    - Comparative Genomics

- id: url:https://icml-compbio.github.io/icml-website-2020/2020/papers/WCBICML2020_paper_23.pdf
  image: images/tools/icml21.jpg
  title: 'Ledidi: Designing genomic edits that induce functional activity'
  authors:
  - 'J Schreiber*'
  - '<b>YY Lu*</b>'
  - William Stafford Noble
  publisher: ICML Workshop on Computational Biology
  date: 2020-7-17
  extra-links:
    - link: https://icml-compbio.github.io/icml-website-2020/2020/papers/WCBICML2020_paper_23.pdf
      text: Paper
    - type: source
      link: https://github.com/jmschrei/ledidi
      text: Code
    - type: docs
      link: https://slideslive.com/38930903/ledidi-designing-genomic-edits-that-induce-functional-activity
      text: Slides
    - type: docs
      link: https://github.com/jmschrei/ledidi/tree/master/tutorials
      text: Tutorial
  tags:
    - Computational Genomics
    - Functional Genomics

- id: url:https://papers.nips.cc/paper/2018/hash/29daf9442f3c0b60642b14c081b4a556-Abstract.html
  image: images/tools/neurips.png
  title: 'DeepPINK: reproducible feature selection in deep neural networks'
  authors:
  - '<b>YY Lu*</b>'
  - 'Y Fan*'
  - J Lv
  - WS Noble
  publisher: Proceedings of International Conference on Neural Information Processing Systems (NeurIPS)
  date: 2018-12-3
  extra-links:
    - link: https://papers.nips.cc/paper/2018/hash/29daf9442f3c0b60642b14c081b4a556-Abstract.html
      text: Paper
    - type: source
      link: https://github.com/younglululu/DeepPINK
      text: Code
    - type: docs
      link: https://www.youtube.com/watch?v=P63aCWa0a8w
      text: Slides
    - type: data
      link: https://noble.gs.washington.edu/proj/DeepPINK/
      text: Datasets
  tags:
    - Error-controlled Machine Learning
    - Knockoff Filter
    - Multiple Hypothesis Testing

- id: url:https://www.proquest.com/openview/d28742f789e37325baa466d61bd8f0d0/1
  image: images/tools/usc.jpg
  title: 'Big Data Analytics in Metagenomics: Integration, Representation, Management, and Visualization'
  authors:
  - '<b>YY Lu</b>'
  publisher: Doctoral Thesis, University of Southern California
  date: 2017-12-1
  extra-links:
    - link: https://www.proquest.com/openview/d28742f789e37325baa466d61bd8f0d0/1
      text: Thesis
  tags:
    - Computational Genomics

- id: doi:10.1093/nar/gkx767
  image: images/tools/nar_heterorp.jpg
  authors:
  - '<b>YY Lu</b>'
  - J Lv
  - JA Fuhrman
  - F Sun
  extra-links:
    - link: https://academic.oup.com/nar/article/45/20/e169/4097616
      text: Paper
    - type: source
      link: https://github.com/younglululu/Hetero-RP
      text: Code
  tags:
    - Computational Genomics
    - Integrative Genomics

- id: doi:10.1093/nar/gkx351
  image: images/tools/nar_cafe.jpg
  authors:
  - '<b>YY Lu</b>'
  - K Tang
  - J Ren
  - JA Fuhrman
  - MS Waterman
  - F Sun
  extra-links:
    - link: https://academic.oup.com/nar/article/45/W1/W554/3791208
      text: Paper
    - type: source
      link: https://github.com/younglululu/CAFE
      text: Code
  tags:
    - Computational Genomics
    - Comparative Genomics

- id: doi:10.1093/bioinformatics/btw290
  image: images/tools/bioinfo_cocacola.jpg
  authors:
  - '<b>YY Lu</b>'
  - T Chen
  - JA Fuhrman
  - F Sun
  extra-links:
    - link: https://academic.oup.com/bioinformatics/article/33/6/791/2525584
      text: Paper
    - type: source
      link: https://github.com/younglululu/COCACOLA
      text: Code
  tags:
    - Computational Genomics
    - Metagenomics


### collaborative papers

- id: doi:10.1101/2022.04.06.487405
  authors:
  - RA Rodriguez-Mias
  - KN Hess
  - BY Ruiz
  - IR Smith
  - AS Barente
  - SM Zimmerman
  - '<b>YY Lu</b>'
  - WS Noble
  - S Fields
  - J Villen
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2022.04.06.487405v1
      text: Preprint
  tags:
    - Computational Proteomics
    - Mass Spectrometry

- id: doi:10.1101/2022.04.11.487945
  authors:
  - AB Dincer
  - '<b>YY Lu</b>'
  - D Schweppe
  - S Oh
  - WS Noble
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2022.04.11.487945v1
      text: Preprint
  tags:
    - Computational Proteomics
    - Mass Spectrometry

- id: doi:10.1093/bioinformatics/btz253
  image: images/tools/bioinfo_cocacola.jpg
  authors:
  - Z Wang
  - Z Wang
  - '<b>YY Lu</b>'
  - F Sun
  - S Zhu
  extra-links:
    - link: https://academic.oup.com/bioinformatics/article/35/21/4229/5448864
      text: Paper
  tags:
    - Computational Genomics
    - Metagenomics

- id: doi:10.1371/journal.pcbi.1007329
  image: images/tools/ploscb.png
  authors:
  - DF Read
  - K Cook
  - '<b>YY Lu</b>'
  - KG Le Roch
  - WS Noble
  extra-links:
    - link: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007329
      text: Paper
  tags:
    - Computational Genomics
    - Functional Genomics

- id: doi:10.1021/acs.jproteome.8b00365
  image: images/tools/jpr_siren.jpg
  authors:
  - A Hu
  - '<b>YY Lu</b>'
  - J Bilmes
  - WS Noble
  extra-links:
    - link: https://pubs.acs.org/doi/10.1021/acs.jproteome.8b00365
      text: Paper
    - type: source
      link: http://bitbucket.org/noblelab/siren
      text: Code
  tags:
    - Computational Proteomics
    - Mass Spectrometry

- id: doi:10.1146/annurev-biodatasci-080917-013431
  image: images/tools/biodatasci.png
  authors:
  - J Ren
  - X Bai
  - '<b>YY Lu</b>'
  - K Tang
  - Y Wang
  - G Reinert
  - F Sun
  extra-links:
    - link: https://www.annualreviews.org/doi/abs/10.1146/annurev-biodatasci-080917-013431
      text: Paper
  tags:
    - Computational Genomics
    - Comparative Genomics
    - Review

- id: doi:10.3389/fmicb.2018.00711
  image: images/tools/frontier_microbiology.jpg
  authors:
  - K Tang
  - '<b>YY Lu</b>'
  - F Sun
  extra-links:
    - link: https://www.frontiersin.org/articles/10.3389/fmicb.2018.00711/full
      text: Paper
  tags:
    - Computational Genomics
    - Comparative Genomics
    - Metagenomics

- id: doi:10.1186/s12859-017-1835-1
  image: images/tools/bmcbioinfo.jpg
  authors:
  - Y Wang
  - K Wang
  - '<b>YY Lu</b>'
  - F Sun
  extra-links:
    - link: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1835-1
      text: Paper
  tags:
    - Computational Genomics
    - Metagenomics

- id: doi:10.1186/s40168-017-0283-5
  image: images/tools/microbiome.png
  authors:
  - J Ren
  - NA Ahlgren
  - '<b>YY Lu</b>'
  - JA Fuhrman
  - F Sun
  extra-links:
    - link: https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-017-0283-5
      text: Paper
  tags:
    - Computational Genomics
    - Metagenomics

- id: doi:10.1093/nar/gkw1002
  image: images/tools/nar_virhostmatcher.jpg
  authors:
  - NA Ahlgren
  - J Ren
  - '<b>YY Lu</b>'
  - JA Fuhrman
  - F Sun
  extra-links:
    - link: https://academic.oup.com/nar/article/45/1/39/2605663
      text: Paper
  tags:
    - Computational Genomics
    - Comparative Genomics
    - Metagenomics
