- id: doi:10.1038/s41592-021-01259-4
  image: images/tools/enformer.jpg
  date: 2021-10-4
  extra-links:
    - link: https://rdcu.be/cyMvt
      text: Paper
  

- id: 1234
  title: test
  author: Yang Lu
  publisher: ICML
  date: 2021-07-18
