- id: doi:10.1038/s41592-021-01259-4
  image: images/tools/enformer.jpg
  date: 2021-10-4
  extra-links:
    - link: https://rdcu.be/cyMvt
      text: Paper
  tags:
    - Computational Genomics

- id: url:https://proceedings.mlr.press/v139/lu21b.html
  image: images/tools/icml21.jpg
  title: 'DANCE: Enhancing saliency maps using decoys'
  publisher: Proceedings of the 38th International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21b.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/dance
      text: Code
    - type: docs
      link: https://slideslive.com/38959260/dance-enhancing-saliency-maps-using-decoys
      text: Slides
  tags:
    - Interpretable Machine Learning

- id: url:https://proceedings.mlr.press/v139/lu21e.html
  image: images/tools/icml21.jpg
  title: 'ACE: Explaining cluster from an adversarial perspective'
  publisher: Proceedings of the 38th International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21e.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/ace
      text: Code
    - type: docs
      link: https://slideslive.com/38959455/ace-explaining-cluster-from-an-adversarial-perspective
      text: Slides
    - type: data
      link: http://noble.gs.washington.edu/proj/ACE
      text: Datasets
  tags:
    - Interpretable Machine Learning
    - Computational Genomics
    - Single-cell Genomics

- id: doi:10.1093/bioinformatics/btab284
  image: images/tools/bioinfo_diameter.jpg
  date: 2021-7-25
  extra-links:
    - link: https://academic.oup.com/bioinformatics/article/37/Supplement_1/i434/6319661
      text: Paper
    - type: source
      link: http://crux.ms/
      text: Code
    - type: docs
      link: files/pubs/diameter_slides.pdf
      text: Slides
    - type: data
      link: http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD025385
      text: Datasets
  tags:
    - Computational Proteomics
    - Mass Spectrometry

- id: doi:10.1093/bioinformatics/btaa699
  image: images/tools/bioinfo_craft.jpg
  date: 2021-1-15
  extra-links:
    - link: https://academic.oup.com/bioinformatics/article/37/2/155/5885078
      text: Paper
    - type: source
      link: https://github.com/jiaxingbai/CRAFT
      text: Code
  tags:
    - Computational Genomics
    - Comparative Genomics
