- id: doi:10.1038/s41592-021-01259-4
  image: images/tools/enformer.jpg
  date: 2021-10-4
  extra-links:
    - link: https://rdcu.be/cyMvt
      text: Paper

- id: url:https://proceedings.mlr.press/v139/lu21b.html
  image: images/tools/icml21.jpg
  title: 'DANCE: Enhancing saliency maps using decoys'
  publisher: Proceedings of the 38th International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21b.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/dance
      text: Code
    - type: docs
      link: https://slideslive.com/38959260/dance-enhancing-saliency-maps-using-decoys
      text: Slides

- id: url:https://proceedings.mlr.press/v139/lu21e.html
  image: images/tools/icml21.jpg
  title: 'ACE: Explaining cluster from an adversarial perspective'
  publisher: Proceedings of the 38th International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21e.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/ace
      text: Code
    - type: docs
      link: https://slideslive.com/38959455/ace-explaining-cluster-from-an-adversarial-perspective
      text: Slides
    - type: data
      link: http://noble.gs.washington.edu/proj/ACE
      text: Datasets
