- id: doi:10.1038/s41592-021-01259-4
  image: images/tools/enformer.jpg
  date: 2021-10-4
  extra-links:
    - link: https://rdcu.be/cyMvt
      text: Paper


- id: url:https://proceedings.mlr.press/v139/lu21b.html
  image: images/tools/icml21.png
  title: 'DANCE: Enhancing saliency maps using decoys'
  publisher: Proceedings of the 38th International Conference on Machine Learning (ICML)
  date: 2021-7-18
  extra-links:
    - link: https://proceedings.mlr.press/v139/lu21b.html
      text: Paper
    - type: source
      link: https://bitbucket.org/noblelab/dance
      text: Code
